apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-ct
  template:
    metadata:
      labels:
        app: web-ct
    spec:
      containers:
        - name: web-ct
          image: jkommisar/conversao-temperatura:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  selector:
    app: web-ct
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30101
